blog/urls.py
from django.conf.urls import patterns, url

from blog.views import PostsListView, PostDetailView, About

urlpatterns = [
    url(r'^$', PostsListView.as_view(), name='index_list'),
    url(r'^page/(?P<page>\d+)/$', PostsListView.as_view(), name='pagination'),
    url(r'about/$', About.as_view(), name='about'),
    url(r'^(?P<slug>[\d\w\-]+)/$', PostDetailView.as_view()),
]

indexPage/urls.py
from django.conf.urls import patterns, url

from .views import IndexPage

urlpatterns = [
    url(r'^$', IndexPage.as_view(), name='index'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('indexPage.urls', namespace="indexPage")),
    url(r'^admin/', admin.site.urls),
    url(r'^markdownx/', include('markdownx.urls')),
    url(r'^blog/', include('blog.urls', namespace="blog")),
]

blog/models.py
from django.db import models
from django.core.urlresolvers import reverse
from markdownx.models import MarkdownxField
from slugify import slugify
from django.contrib.auth.models import User

# Create your models here.


class Tag(models.Model):
    name = models.CharField(max_length=127, verbose_name='Назва тегу')

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=255, verbose_name='Назва')
    slug = models.SlugField(unique=True, max_length=255, blank=True, verbose_name='Slug')
    description = models.CharField(max_length=255, verbose_name='Короткий опис')
    description_image = models.CharField(max_length=255, default="")
    content = MarkdownxField(verbose_name='Контент')                              # models.TextField()
    published = models.BooleanField(default=True, verbose_name='Опубліковано?')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')
    last_accessed = models.DateTimeField(verbose_name='Останній перегляд')
    last_accessed_ip = models.GenericIPAddressField(default='127.0.0.1', verbose_name='IP-адреса останнього відвідувача')
    original_link = models.URLField(default='', verbose_name='Посилання на оригінал')
    author = models.ForeignKey(User, default=1, verbose_name='Автор')
    tags = models.ManyToManyField(Tag)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return "/blog/{0}/".format(self.slug)

indexPage/models.py
from django.db import models

# Create your models here.

blog/forms.py
from markdownx import forms
from markdownx.fields import MarkdownxFormField


class MyForm(forms.Form):

    myfield = MarkdownxFormField()

blog/views.py
from django.shortcuts import render
from django.views.generic import View, ListView, DetailView
from blog.models import Post
from django.utils import timezone


# Create your views here.


class PostsListView(ListView):
    model = Post
    paginate_by = 10
    template_name = 'blog/index.html'
    context_object_name = 'my_all_posts'


class PostDetailView(DetailView):
    queryset = Post.objects.all()
    template_name = 'blog/showpost.html'

    def get_object(self):
        # Call the superclass
        object = super(PostDetailView, self).get_object()
        # Record the last accessed date
        object.last_accessed = timezone.now()
        object.save()
        # Return the object
        return object


class About(View):
    def get(self, request):
        return render(request, "blog/about.html", {})

    def post(self):
        pass

indexPage/views.py
from django.shortcuts import render
from django.views.generic import View

# Create your views here.


class IndexPage(View):
    def get(self, request):
        return render(request, 'indexPage/index.html')

    def post(self):
        pass

blog/templates/blog/about.html
{% extends 'base.html' %}
{% load markdown_deux_tags %}

{% block title %}
About
{% endblock %}

{% block content %}
    <div class="post z-depth-1">
            <div class="post-info">
                Антон М.
            </div>
    </div>
{% endblock %}

blog/templates/blog/index.html
{% extends 'base.html' %}

{% block title %}
Main Page
{% endblock %}


{% block content %}

    {% for post in my_all_posts %}
        <div class="post z-depth-1 hoverable">
            <div class="post-info">
                <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
                <p class="descr_image"><img src="{{ post.description_image }}" style="width: 50%;"/></p>
                <p align="justify">{{ post.description }}</p>
                <p align="justify">Posted on {{ post.created|date }} by <b>{{ post.author }}</b></p>
            </div>
        </div>
        {% empty %}
        <p>Статей не обнаружено :(</p>
    {% endfor %}

<div class="paginator" align="center">
{% if paginator.num_pages > 1 %}
    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li class="waves-effect">
                <a href="{% url 'blog:pagination' page_obj.previous_page_number %}">
                    <i class="material-icons">chevron_left</i>
                </a>
            </li>
        {% else %}
            <li class="disabled"><a href="#!"><i class="material-icons">chevron_left</i></a></li>
        {% endif %}
        {% if paginator.num_pages < 10 %}
            {% if page_obj.has_previous %}
            <li><a href="{% url 'blog:pagination' page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a></li>
            {% endif %}
            <li class="active"><a href="#!">{{ page_obj.number }}</a></li>
            {% if page_obj.has_next %}
            <li><a href="{% url 'blog:pagination' page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a></li>
            {% endif %}
        {% endif %}
        {% if page_obj.has_next %}
            <li class="waves-effect">
                <a href="{% url 'blog:pagination' page_obj.next_page_number %}">
                    <i class="material-icons">chevron_right</i>
                </a>
            </li>
        {% else %}
            <li class="disabled"><a href="#!"><i class="material-icons">chevron_right</i></a></li>
        {% endif %}
    </ul>
{% endif %}
</div>

{% endblock %}

blog/templates/blog/showpost.html
{% extends 'base.html' %}
{% load markdown_deux_tags %}

{% block title %}
{{ object.title|title }}
{% endblock %}

{% block content %}
    <div class="post z-depth-1">
            <div class="post-info">
                <h4>{{ post.title }}</h4>
                <p>Posted on {{ post.created|date }}</p>
                <p>{{ post.description }}</p>
                {{ post.content|markdown }}
                {% for tag in post.tags.all %}
                <div class="chip">{{ tag }}</div>
                {% endfor %}
            </div>
    </div>
{% endblock %}

indexPage/templates/indexPage/index.html
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <title>Material UI One Page Theme</title>

    <!-- CSS  -->
    <link href="min/plugin-min.css" type="text/css" rel="stylesheet">
    <link href="min/custom-min.css" type="text/css" rel="stylesheet" >
</head>
<body id="top" class="scrollspy">

<!--Navigation-->
 <div class="navbar-fixed">
    <nav id="nav_f" class="default_color" role="navigation">
        <div class="container">
            <div class="nav-wrapper">
            <a href="#" id="logo-container" class="brand-logo">Phonxiss site</a>
                <ul class="right hide-on-med-and-down">
                    <li><a href="#intro">Service</a></li>
                    <li><a href="#work">Work</a></li>
                    <li><a href="#team">Team</a></li>
                    <li><a href="#contact">Contact</a></li>
                </ul>
                <ul id="nav-mobile" class="side-nav">
                    <li><a href="#intro">Service</a></li>
                    <li><a href="#work">Work</a></li>
                    <li><a href="#team">Team</a></li>
                    <li><a href="#contact">Contact</a></li>
                </ul>
            <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
            </div>
        </div>
    </nav>
</div>

<!--Hero-->
<div class="section no-pad-bot" id="index-banner">
    <div class="container">
        <h1 class="text_h center header cd-headline letters type">
            <span>Я love</span> 
            <span class="cd-words-wrapper waiting">
                <b class="is-visible">Python</b>
                <b>Django</b>
                <b>self</b>
            </span>
        </h1>
    </div>
</div>


    <!--  Scripts-->
    <script src="min/plugin-min.js"></script>
    <script src="min/custom-min.js"></script>

    </body>
</html>

templates/base.html
{% load staticfiles %}
<html>

<head>
    <link href="{% static 'blog/css/materialize.css' %}" rel="stylesheet" media="screen" />
    <link href="{% static 'blog/css/style.css' %}" rel="stylesheet" media="screen" />
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Gloria+Hallelujah" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>
<body>
    <header>
        <nav class="transparent">
            <div class="nav-wrapper container">
                <a href="/blog" class="brand-logo brand-logo-small black-text">Phonxis</a>
                <ul class="right hide-on-med-and-down">
                    <li><a href="{% url 'indexPage:index' %}">Main</a></li>
                    <li><a href="{% url 'blog:about' %}">About</a></li>
                </ul>
                <ul id="menu" class="side-nav" style="display: none;">
                    <li><a href="{% url 'indexPage:index' %}">Main</a></li>
                    <li><a href="{% url 'blog:about' %}">About</a></li>
                </ul>
                <div class="menu-trigger hide-on-large-only" id="trigger" data-activates="mobile-demo"><i class="material-icons">menu</i></div>
            </div>
        </nav>
    </header>

    <div class="container">
        {% block content %}

        {% endblock %}
    </div>
    <script src="{% static 'blog/js/jquery-2.1.1.min.js' %}"></script>
    <script src="{% static 'blog/js/materialize.js' %}"></script>
    <script src="{% static 'blog/js/panel.js' %}"></script>
    <script type="text/javascript">
        $(document).ready(function(){
            $('p').attr('align', 'justify');
            $('h1').css('font-family', "'Gloria Hallelujah', cursive, serif");
            $(".button-collapse").sideNav();
        });
    </script>
    <script type="text/javascript">
        $(document).ready(function () {
            var jPM = $.jPanelMenu();
            jPM.on();
        });
    </script>s
</body>
</html>

templates/indexPage/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <title>Main</title>

    <!-- CSS  -->
    <link href="{% static 'indexPage/css/plugin-min.css' %}" type="text/css" rel="stylesheet">
    <link href="{% static 'indexPage/css/custom-min.css' %}" type="text/css" rel="stylesheet" >
</head>
<body id="top" class="scrollspy">

<!--Navigation-->
 <div class="navbar-fixed">
    <nav id="nav_f" class="default_color" role="navigation">
        <div class="container">
            <div class="nav-wrapper">
            <a href="#" id="logo-container" class="brand-logo">Phonxis</a>
                <ul class="right hide-on-med-and-down">
                    <li><a href="{% url 'blog:index_list' %}">Blog</a></li>
                    <li><a href="{% url 'blog:about' %}">About</a></li>
                </ul>
                <ul id="nav-mobile" class="side-nav">
                    <li><a href="{% url 'blog:index_list' %}">Blog</a></li>
                    <li><a href="{% url 'blog:about' %}">About</a></li>
                </ul>
            <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
            </div>
        </div>
    </nav>
</div>

<!--Hero-->
<div class="section no-pad-bot" id="index-banner">
    <div class="container">
        <h1 class="text_h center header cd-headline letters type">
            <span>Я love</span> 
            <span class="cd-words-wrapper waiting">
                <b class="is-visible">Python</b>
                <b>Django</b>
                <b>JS</b>
            </span>
        </h1>
    </div>
</div>

    <!--  Scripts-->
    <script src="{% static 'indexPage/js/plugin-min.js' %}"></script>
    <script src="{% static 'indexPage/js/custom-min.js' %}"></script>

    </body>
</html>